import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../data/settings.dart';
import '../data/db.dart';
import '../services/cloud_backup_service.dart';
import '../services/manager_auth.dart';

class SettingsScreen extends StatefulWidget {
  const SettingsScreen({super.key});
  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  final _form = GlobalKey<FormState>();
  late final TextEditingController _nameCtrl;
  late final TextEditingController _vatCtrl;
  late final TextEditingController _taxCtrl;
  late final TextEditingController _currencyCtrl;
  bool _includeVat = true;
  bool _autoClassifyExpenses = true;
  bool _autoPostTransactions = true;
  bool _autoMarkOverdue = true;
  bool _autoGenerateMonthlyClose = true;
  bool _deletingAccount = false;

  @override
  void initState() {
    super.initState();
    final s = AppSettings.instance;
    _nameCtrl = TextEditingController(text: s.businessName);
    _vatCtrl = TextEditingController(text: s.vatReg);
    _taxCtrl =
        TextEditingController(text: (s.taxRate * 100).toStringAsFixed(2));
    _currencyCtrl = TextEditingController(text: s.currencySymbol);
    _includeVat = s.pricesIncludeVat;
    _autoClassifyExpenses = s.autoClassifyExpenses;
    _autoPostTransactions = s.autoPostTransactions;
    _autoMarkOverdue = s.autoMarkOverdue;
    _autoGenerateMonthlyClose = s.autoGenerateMonthlyClose;
    CloudBackupService.instance.addListener(_onCloudBackupChanged);
    unawaited(CloudBackupService.instance.bootstrap());
  }

  @override
  void dispose() {
    CloudBackupService.instance.removeListener(_onCloudBackupChanged);
    _nameCtrl.dispose();
    _vatCtrl.dispose();
    _taxCtrl.dispose();
    _currencyCtrl.dispose();
    super.dispose();
  }

  void _onCloudBackupChanged() {
    if (mounted) setState(() {});
  }

  Future<void> _save() async {
    if (!_form.currentState!.validate()) return;
    final s = AppSettings.instance;
    s.businessName =
        _nameCtrl.text.trim().isEmpty ? 'My Car Wash' : _nameCtrl.text.trim();
    s.vatReg = _vatCtrl.text.trim();
    s.taxRate = (double.tryParse(_taxCtrl.text.trim()) ?? 15) / 100.0;
    s.currencySymbol =
        _currencyCtrl.text.trim().isEmpty ? 'R' : _currencyCtrl.text.trim();
    s.pricesIncludeVat = _includeVat;
    s.autoClassifyExpenses = _autoClassifyExpenses;
    s.autoPostTransactions = _autoPostTransactions;
    s.autoMarkOverdue = _autoMarkOverdue;
    s.autoGenerateMonthlyClose = _autoGenerateMonthlyClose;
    await s.saveAll();
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Settings saved')),
      );
      setState(() {});
    }
  }

  Future<void> _shareBackup() async {
    final bytes = await AppDb.instance.exportBytes();
    final dir = await getTemporaryDirectory();
    final dbPath = File(
      '${dir.path}/washdesk_backup_${DateTime.now().millisecondsSinceEpoch}.db',
    );
    await dbPath.writeAsBytes(bytes, flush: true);
    await Share.shareXFiles([
      XFile(dbPath.path,
          mimeType: 'application/octet-stream', name: 'washdesk_backup.db'),
    ],
        subject: 'WashDesk Backup',
        text: 'SQLite backup file generated by the app.');
  }

  Future<void> _backUpToCloud() async {
    final account = ManagerAuth.instance.current;
    if (account == null) {
      _showSnack('Sign in before backing up to cloud.');
      return;
    }
    try {
      final result = await CloudBackupService.instance.backupNow(account);
      if (!mounted) return;
      _showSnack('${result.message} (${_formatBytes(result.sizeBytes)})');
    } on StateError catch (e) {
      if (!mounted) return;
      _showSnack(e.message);
    } catch (e) {
      if (!mounted) return;
      _showSnack('Cloud backup failed: $e');
    }
  }

  Future<void> _restoreFromCloud() async {
    final account = ManagerAuth.instance.current;
    if (account == null) {
      _showSnack('Sign in before restoring a cloud backup.');
      return;
    }
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Restore cloud backup?'),
          content: const Text(
            'This replaces the data on this device with the latest cloud '
            'backup for the signed-in account.',
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () => Navigator.pop(context, true),
              child: const Text('Restore'),
            ),
          ],
        );
      },
    );
    if (confirmed != true) return;

    try {
      final result = await CloudBackupService.instance.restoreLatest(account);
      _applySettingsToFields();
      if (!mounted) return;
      _showSnack('${result.message} (${_formatBytes(result.sizeBytes)})');
      setState(() {});
    } on StateError catch (e) {
      if (!mounted) return;
      _showSnack(e.message);
    } catch (e) {
      if (!mounted) return;
      _showSnack('Cloud restore failed: $e');
    }
  }

  void _applySettingsToFields() {
    final s = AppSettings.instance;
    _nameCtrl.text = s.businessName;
    _vatCtrl.text = s.vatReg;
    _taxCtrl.text = (s.taxRate * 100).toStringAsFixed(2);
    _currencyCtrl.text = s.currencySymbol;
    _includeVat = s.pricesIncludeVat;
    _autoClassifyExpenses = s.autoClassifyExpenses;
    _autoPostTransactions = s.autoPostTransactions;
    _autoMarkOverdue = s.autoMarkOverdue;
    _autoGenerateMonthlyClose = s.autoGenerateMonthlyClose;
  }

  void _showSnack(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message)),
    );
  }

  Future<void> _changePassword() async {
    final form = GlobalKey<FormState>();
    final currentCtrl = TextEditingController();
    final nextCtrl = TextEditingController();
    try {
      final confirmed = await showDialog<bool>(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: const Text('Change password'),
            content: Form(
              key: form,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextFormField(
                    controller: currentCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Current password',
                    ),
                    obscureText: true,
                    validator: _required('Enter your current password'),
                  ),
                  const SizedBox(height: 10),
                  TextFormField(
                    controller: nextCtrl,
                    decoration: const InputDecoration(
                      labelText: 'New password',
                    ),
                    obscureText: true,
                    validator: (value) {
                      final text = value?.trim() ?? '';
                      if (text.length < 8) return 'Use at least 8 characters';
                      return null;
                    },
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context, false),
                child: const Text('Cancel'),
              ),
              FilledButton(
                onPressed: () {
                  if (form.currentState!.validate()) {
                    Navigator.pop(context, true);
                  }
                },
                child: const Text('Update'),
              ),
            ],
          );
        },
      );
      if (confirmed != true) return;
      await ManagerAuth.instance.changePassword(
        currentPassword: currentCtrl.text,
        newPassword: nextCtrl.text,
      );
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Password updated')),
      );
    } on StateError catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(e.message)),
      );
    } finally {
      currentCtrl.dispose();
      nextCtrl.dispose();
    }
  }

  Future<void> _signOut() async {
    await ManagerAuth.instance.logout();
    if (!mounted) return;
    Navigator.pushNamedAndRemoveUntil(context, '/onboarding', (_) => false);
  }

  Future<void> _deleteAccount(ManagerAccount account) async {
    final firstConfirm = await showDialog<bool>(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text('Delete WashDesk account?'),
          content: const Text(
            'This permanently deletes this manager account and the WashDesk '
            'business data stored on this device, including bookings, washes, '
            'customers, employees, services, expenses, reports and backups '
            'state. If cloud backup is configured, the cloud account and '
            'backup files are deleted too. This cannot be undone.\n\n'
            'Your App Store subscription is managed by Apple and must be '
            'cancelled from your Apple account if you no longer want it to '
            'renew.',
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel'),
            ),
            FilledButton(
              style: FilledButton.styleFrom(
                backgroundColor: Theme.of(context).colorScheme.error,
                foregroundColor: Theme.of(context).colorScheme.onError,
              ),
              onPressed: () => Navigator.pop(context, true),
              child: const Text('Continue'),
            ),
          ],
        );
      },
    );
    if (firstConfirm != true || !mounted) return;

    final form = GlobalKey<FormState>();
    final emailCtrl = TextEditingController();
    try {
      final finalConfirm = await showDialog<bool>(
        context: context,
        builder: (context) {
          return AlertDialog(
            title: const Text('Confirm deletion'),
            content: Form(
              key: form,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Type ${account.email} to permanently delete this account.',
                  ),
                  const SizedBox(height: 12),
                  TextFormField(
                    controller: emailCtrl,
                    decoration: const InputDecoration(
                      labelText: 'Account email',
                    ),
                    keyboardType: TextInputType.emailAddress,
                    textInputAction: TextInputAction.done,
                    validator: (value) {
                      if ((value ?? '').trim().toLowerCase() !=
                          account.email.toLowerCase()) {
                        return 'Enter the signed-in account email.';
                      }
                      return null;
                    },
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context, false),
                child: const Text('Cancel'),
              ),
              FilledButton(
                style: FilledButton.styleFrom(
                  backgroundColor: Theme.of(context).colorScheme.error,
                  foregroundColor: Theme.of(context).colorScheme.onError,
                ),
                onPressed: () {
                  if (form.currentState!.validate()) {
                    Navigator.pop(context, true);
                  }
                },
                child: const Text('Delete account'),
              ),
            ],
          );
        },
      );
      if (finalConfirm != true || !mounted) return;

      setState(() => _deletingAccount = true);
      await ManagerAuth.instance.deleteCurrentAccount();
      if (!mounted) return;
      Navigator.pushNamedAndRemoveUntil(context, '/onboarding', (_) => false);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('WashDesk account deleted')),
      );
    } on StateError catch (e) {
      if (!mounted) return;
      _showSnack(e.message);
    } catch (e) {
      if (!mounted) return;
      _showSnack('Account deletion failed: $e');
    } finally {
      emailCtrl.dispose();
      if (mounted) setState(() => _deletingAccount = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Settings')),
      body: Form(
        key: _form,
        child: ListView(
          padding: const EdgeInsets.fromLTRB(18, 24, 18, 48),
          children: [
            const Text('Account',
                style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            ValueListenableBuilder<ManagerAccount?>(
              valueListenable: ManagerAuth.instance.listenable,
              builder: (context, account, _) {
                if (account == null) {
                  return const Text('No manager account is signed in.');
                }
                final status = account.isActive
                    ? 'Subscription active'
                    : account.hasAccess
                        ? '${account.trialDaysRemaining} trial day${account.trialDaysRemaining == 1 ? '' : 's'} left'
                        : 'Trial expired';
                return Card(
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          account.businessName,
                          style: Theme.of(context)
                              .textTheme
                              .titleMedium
                              ?.copyWith(fontWeight: FontWeight.w800),
                        ),
                        const SizedBox(height: 4),
                        Text('${account.ownerName} • ${account.email}'),
                        const SizedBox(height: 8),
                        Chip(label: Text(status)),
                        const SizedBox(height: 8),
                        Row(
                          children: [
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: _changePassword,
                                icon: const Icon(Icons.lock_reset_rounded),
                                label: const Text('Password'),
                              ),
                            ),
                            const SizedBox(width: 10),
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: _signOut,
                                icon: const Icon(Icons.logout_rounded),
                                label: const Text('Sign out'),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        SizedBox(
                          width: double.infinity,
                          child: OutlinedButton.icon(
                            style: OutlinedButton.styleFrom(
                              foregroundColor:
                                  Theme.of(context).colorScheme.error,
                              side: BorderSide(
                                color: Theme.of(context)
                                    .colorScheme
                                    .error
                                    .withValues(alpha: 0.55),
                              ),
                            ),
                            onPressed: _deletingAccount
                                ? null
                                : () => _deleteAccount(account),
                            icon: _deletingAccount
                                ? const SizedBox.square(
                                    dimension: 18,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                    ),
                                  )
                                : const Icon(Icons.delete_forever_rounded),
                            label: Text(
                              _deletingAccount
                                  ? 'Deleting account'
                                  : 'Delete account',
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
            const SizedBox(height: 20),
            const Text('Business',
                style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            TextFormField(
              controller: _nameCtrl,
              decoration: const InputDecoration(labelText: 'Business name'),
            ),
            const SizedBox(height: 8),
            TextFormField(
              controller: _vatCtrl,
              decoration: const InputDecoration(
                  labelText: 'VAT reg. number (optional)'),
            ),
            const SizedBox(height: 16),
            const Text('Tax & Currency',
                style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            TextFormField(
              controller: _taxCtrl,
              decoration: const InputDecoration(labelText: 'Tax rate (%)'),
              keyboardType: TextInputType.number,
              validator: (v) {
                final n = double.tryParse(v ?? '');
                if (n == null || n < 0 || n > 100) {
                  return 'Enter a valid percentage';
                }
                return null;
              },
            ),
            const SizedBox(height: 8),
            TextFormField(
              controller: _currencyCtrl,
              decoration: const InputDecoration(labelText: 'Currency symbol'),
              maxLength: 3,
            ),
            const SizedBox(height: 8),
            SwitchListTile(
              title: const Text('Prices include tax (VAT)'),
              value: _includeVat,
              onChanged: (v) => setState(() => _includeVat = v),
            ),
            const SizedBox(height: 16),
            const Text('Automation',
                style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            SwitchListTile(
              title: const Text('Auto classify expenses'),
              subtitle:
                  const Text('Use vendor/note rules to pick expense category'),
              value: _autoClassifyExpenses,
              onChanged: (v) => setState(() => _autoClassifyExpenses = v),
            ),
            SwitchListTile(
              title: const Text('Auto post transactions'),
              subtitle: const Text(
                  'Auto-create accounting entries for washes and expenses'),
              value: _autoPostTransactions,
              onChanged: (v) => setState(() => _autoPostTransactions = v),
            ),
            SwitchListTile(
              title: const Text('Auto mark overdue invoices/bills'),
              subtitle: const Text(
                  'Automatically update statuses by due date and balance'),
              value: _autoMarkOverdue,
              onChanged: (v) => setState(() => _autoMarkOverdue = v),
            ),
            SwitchListTile(
              title: const Text('Auto generate monthly close'),
              subtitle: const Text(
                  'Keep monthly profit, VAT and AR/AP snapshots up to date'),
              value: _autoGenerateMonthlyClose,
              onChanged: (v) => setState(() => _autoGenerateMonthlyClose = v),
            ),
            const SizedBox(height: 24),
            FilledButton.icon(
              onPressed: _save,
              icon: const Icon(Icons.save),
              label: const Text('Save'),
            ),
            const SizedBox(height: 24),
            const Text('Data', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            _CloudBackupCard(
              service: CloudBackupService.instance,
              onBackup: _backUpToCloud,
              onRestore: _restoreFromCloud,
            ),
            const SizedBox(height: 10),
            OutlinedButton.icon(
              onPressed: _shareBackup,
              icon: const Icon(Icons.ios_share),
              label: const Text('Export offline backup'),
            ),
            const SizedBox(height: 24),
            const Text('Legal', style: TextStyle(fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () => Navigator.pushNamed(context, '/terms'),
                    icon: const Icon(Icons.description_outlined),
                    label: const Text('Terms'),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: () => Navigator.pushNamed(context, '/privacy'),
                    icon: const Icon(Icons.privacy_tip_outlined),
                    label: const Text('Privacy'),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _CloudBackupCard extends StatelessWidget {
  final CloudBackupService service;
  final VoidCallback onBackup;
  final VoidCallback onRestore;

  const _CloudBackupCard({
    required this.service,
    required this.onBackup,
    required this.onRestore,
  });

  @override
  Widget build(BuildContext context) {
    final configured = service.isConfigured;
    final busy = service.isBusy;
    final lastBackup = service.lastBackupAt;
    final status = configured
        ? lastBackup == null
            ? 'Ready for the first cloud backup'
            : 'Last backup ${_formatDateTime(lastBackup)}'
        : 'Add Supabase keys to enable secure cloud backup.';

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  width: 42,
                  height: 42,
                  decoration: BoxDecoration(
                    color: Theme.of(context)
                        .colorScheme
                        .primaryContainer
                        .withValues(alpha: 0.75),
                    borderRadius: BorderRadius.circular(14),
                  ),
                  child: Icon(
                    configured
                        ? Icons.cloud_done_rounded
                        : Icons.cloud_off_rounded,
                    color: Theme.of(context).colorScheme.onPrimaryContainer,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Cloud backup',
                        style: Theme.of(context)
                            .textTheme
                            .titleMedium
                            ?.copyWith(fontWeight: FontWeight.w800),
                      ),
                      const SizedBox(height: 2),
                      Text(status),
                    ],
                  ),
                ),
              ],
            ),
            if (!configured) ...[
              const SizedBox(height: 12),
              Text(
                'Build with WASHDESK_SUPABASE_URL and '
                'WASHDESK_SUPABASE_ANON_KEY.',
                style: Theme.of(context).textTheme.bodySmall,
              ),
            ],
            const SizedBox(height: 14),
            Row(
              children: [
                Expanded(
                  child: FilledButton.icon(
                    onPressed: configured && !busy ? onBackup : null,
                    icon: busy
                        ? const SizedBox(
                            width: 18,
                            height: 18,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Icon(Icons.cloud_upload_rounded),
                    label: const Text('Back up'),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: OutlinedButton.icon(
                    onPressed: configured && !busy ? onRestore : null,
                    icon: const Icon(Icons.cloud_download_rounded),
                    label: const Text('Restore'),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

String? Function(String?) _required(String message) {
  return (value) {
    if (value == null || value.trim().isEmpty) return message;
    return null;
  };
}

String _formatDateTime(DateTime value) {
  final local = value.toLocal();
  final day = local.day.toString().padLeft(2, '0');
  final month = local.month.toString().padLeft(2, '0');
  final hour = local.hour.toString().padLeft(2, '0');
  final minute = local.minute.toString().padLeft(2, '0');
  return '$day/$month/${local.year} at $hour:$minute';
}

String _formatBytes(int bytes) {
  if (bytes < 1024) return '$bytes B';
  final kb = bytes / 1024;
  if (kb < 1024) return '${kb.toStringAsFixed(1)} KB';
  final mb = kb / 1024;
  return '${mb.toStringAsFixed(1)} MB';
}
